# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 18:04
from __future__ import unicode_literals

import core.files
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', max_length=255, null=True, upload_to=core.files.UploadToDir('avatars/', random_name=True)),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_address',
            field=models.TextField(blank=True, help_text='Dirección que por defecto se usará para crear trayectos', null=True, verbose_name='dirección por defecto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_distance',
            field=models.PositiveIntegerField(blank=True, default=500, help_text='Distancia máxima que se utilizará para encontrar trayectos (metros)', null=True, verbose_name='distancia por defecto'),
        ),
    ]
