# Dockerfile for Backstage App
FROM ubuntu:16.04
ENV PYTHONUNBUFFERED 1
MAINTAINER Marcos Gabarda <hey@marcosgabarda.com>

# Ubuntu packages required
RUN apt-get update && apt-get install -y \
     software-properties-common
RUN add-apt-repository multiverse
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    python3 \
    python3-dev \
    python3-pip \
    libjpeg-dev \
    jpegoptim \
    optipng \
    gettext \
    gdal-bin \
    geoip-bin \
    geoip-database-contrib \
    libspatialite-dev \
    libspatialite7 \
    spatialite-bin \
    libsqlite3-mod-spatialite \
    curl

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip3 install -U pip
RUN pip3 install -r /requirements/local.txt

# Copy entrypoint script
COPY ./compose/app/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Copy script for starting development server
COPY ./compose/app/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh
RUN chmod +x /start-dev.sh

# Set working directory
WORKDIR /app/upvcarshare

ENTRYPOINT ["/entrypoint.sh"]
