# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_auto_20160523_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='free_places',
            field=models.PositiveIntegerField(blank=True, default=4, null=True, verbose_name='plazas libres'),
        ),
    ]
