# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0005_auto_20160610_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Confiramado'), (1, 'Rechazado'), (2, 'Desconocido')], default=2),
        ),
    ]
