# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0006_passenger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.Transport', verbose_name='Medio de transporte utilizado'),
        ),
        migrations.AddField(
            model_name='transport',
            name='brand',
            field=models.TextField(blank=True, default='', max_length=250, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='transport',
            name='color',
            field=models.TextField(blank=True, default='', max_length=250, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='transport',
            name='model',
            field=models.TextField(blank=True, default='', max_length=250, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='default_places',
            field=models.PositiveIntegerField(default=4, verbose_name='Plazas libres'),
        ),
    ]
