# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0007_auto_20160620_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='journeys.Transport', verbose_name='Medio de transporte utilizado'),
        ),
    ]
