# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0008_auto_20160620_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='journeys.Campus', verbose_name='campus'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='journeys.Residence', verbose_name='lugar'),
        ),
    ]
