# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0010_auto_20160706_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.Journey'),
        ),
    ]
